export const tagTypes = {
  GET_USER: "GET_USER",
  GET_CUSTOMERS: "GET_CUSTOMERS",
  GET_STAFFS: "GET_STAFFS",
  GET_GROUPS: "GET_GROUPS",
  GET_GROUPS_UNPAGINATED: "GET_GROUPS_UNPAGINATED",
  GET_ROLES: "GET_ROLES",
  GET_UNPAGINATED_ROLES: "GET_UNPAGINATED_ROLES",
  GET_PERMISSIONS: "GET_PERMISSIONS",
};
